queryParameters: 
  filter: 
    description: |
      Issues assigned to you / created by you / mentioning you / you're
      subscribed to updates for / All issues the authenticated user can see
    enum:
      - assigned
      - created
      - mentioned
      - subscribed
      - all
    default: all
  state: 
    enum: [ open , closed ]
    default: open
  labels: 
    description: String list of comma separated Label names. Example - bug,ui,@high.
  sort:
    enum:
      - created
      - updated
      - comments
    default: created
  direction: 
    enum: [ asc , desc ]
    default: desc
  since: 
    description: |
      Optional string of a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
      Only issues updated at or after this time are returned.
